kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chatbot2b-sep26-1-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: chatbot2b-sep26-1-dsp-job
    namespace: chatbot2b-sep26-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chatbot2b-sep26-1-imagestream-job-role
